# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pssGraphics.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(670, 600)
        MainWindow.setMinimumSize(QtCore.QSize(670, 600))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("pss_ico.ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon.addPixmap(QtGui.QPixmap("../../.designer/backup/pss_ico.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMaximumSize(QtCore.QSize(5000, 5000))
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 150))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.data_view = QtWidgets.QTreeWidget(self.groupBox)
        self.data_view.setEnabled(False)
        self.data_view.setMaximumSize(QtCore.QSize(16777215, 200))
        self.data_view.setFocusPolicy(QtCore.Qt.NoFocus)
        self.data_view.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.data_view.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.data_view.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.data_view.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.data_view.setAlternatingRowColors(True)
        self.data_view.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.data_view.setRootIsDecorated(True)
        self.data_view.setUniformRowHeights(True)
        self.data_view.setAnimated(True)
        self.data_view.setAllColumnsShowFocus(True)
        self.data_view.setHeaderHidden(False)
        self.data_view.setObjectName("data_view")
        self.data_view.header().setCascadingSectionResizes(False)
        self.data_view.header().setDefaultSectionSize(300)
        self.data_view.header().setHighlightSections(True)
        self.data_view.header().setMinimumSectionSize(300)
        self.data_view.header().setStretchLastSection(True)
        self.verticalLayout.addWidget(self.data_view)
        self.gridLayout_2.addWidget(self.groupBox, 2, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.div_line_2 = QtWidgets.QFrame(self.centralwidget)
        self.div_line_2.setMinimumSize(QtCore.QSize(600, 4))
        self.div_line_2.setMaximumSize(QtCore.QSize(5000, 4))
        self.div_line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.div_line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.div_line_2.setObjectName("div_line_2")
        self.gridLayout.addWidget(self.div_line_2, 1, 1, 1, 5)
        self.f1_input_label = QtWidgets.QLabel(self.centralwidget)
        self.f1_input_label.setMinimumSize(QtCore.QSize(100, 20))
        self.f1_input_label.setMaximumSize(QtCore.QSize(100, 20))
        self.f1_input_label.setObjectName("f1_input_label")
        self.gridLayout.addWidget(self.f1_input_label, 0, 1, 1, 1)
        self.div_line_1 = QtWidgets.QFrame(self.centralwidget)
        self.div_line_1.setMinimumSize(QtCore.QSize(4, 20))
        self.div_line_1.setMaximumSize(QtCore.QSize(4, 20))
        self.div_line_1.setFrameShape(QtWidgets.QFrame.VLine)
        self.div_line_1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.div_line_1.setObjectName("div_line_1")
        self.gridLayout.addWidget(self.div_line_1, 0, 3, 1, 1)
        self.f2_input_label = QtWidgets.QLabel(self.centralwidget)
        self.f2_input_label.setMinimumSize(QtCore.QSize(100, 20))
        self.f2_input_label.setMaximumSize(QtCore.QSize(100, 20))
        self.f2_input_label.setObjectName("f2_input_label")
        self.gridLayout.addWidget(self.f2_input_label, 0, 4, 1, 1)
        self.solve_punnett_square_button = QtWidgets.QPushButton(self.centralwidget)
        self.solve_punnett_square_button.setEnabled(False)
        self.solve_punnett_square_button.setMinimumSize(QtCore.QSize(600, 30))
        self.solve_punnett_square_button.setMaximumSize(QtCore.QSize(5000, 50))
        self.solve_punnett_square_button.setCheckable(False)
        self.solve_punnett_square_button.setAutoRepeat(False)
        self.solve_punnett_square_button.setAutoExclusive(False)
        self.solve_punnett_square_button.setAutoDefault(False)
        self.solve_punnett_square_button.setDefault(True)
        self.solve_punnett_square_button.setFlat(False)
        self.solve_punnett_square_button.setObjectName("solve_punnett_square_button")
        self.gridLayout.addWidget(self.solve_punnett_square_button, 2, 1, 1, 5)
        self.f2_input = QtWidgets.QLineEdit(self.centralwidget)
        self.f2_input.setMinimumSize(QtCore.QSize(100, 20))
        self.f2_input.setMaximumSize(QtCore.QSize(2000, 20))
        self.f2_input.setMaxLength(20)
        self.f2_input.setObjectName("f2_input")
        self.gridLayout.addWidget(self.f2_input, 0, 5, 1, 1)
        self.div_line_3 = QtWidgets.QFrame(self.centralwidget)
        self.div_line_3.setMinimumSize(QtCore.QSize(600, 4))
        self.div_line_3.setMaximumSize(QtCore.QSize(5000, 4))
        self.div_line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.div_line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.div_line_3.setObjectName("div_line_3")
        self.gridLayout.addWidget(self.div_line_3, 3, 1, 1, 5)
        self.f1_input = QtWidgets.QLineEdit(self.centralwidget)
        self.f1_input.setMinimumSize(QtCore.QSize(100, 20))
        self.f1_input.setMaximumSize(QtCore.QSize(2000, 20))
        self.f1_input.setMaxLength(20)
        self.f1_input.setDragEnabled(False)
        self.f1_input.setObjectName("f1_input")
        self.gridLayout.addWidget(self.f1_input, 0, 2, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setMinimumSize(QtCore.QSize(650, 300))
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.cross_label = QtWidgets.QLabel(self.groupBox_2)
        self.cross_label.setEnabled(True)
        self.cross_label.setMinimumSize(QtCore.QSize(600, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.cross_label.setFont(font)
        self.cross_label.setFrameShape(QtWidgets.QFrame.Box)
        self.cross_label.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.cross_label.setLineWidth(2)
        self.cross_label.setText("")
        self.cross_label.setAlignment(QtCore.Qt.AlignCenter)
        self.cross_label.setObjectName("cross_label")
        self.verticalLayout_2.addWidget(self.cross_label)
        self.punnett_square_view = QtWidgets.QTableWidget(self.groupBox_2)
        self.punnett_square_view.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.punnett_square_view.sizePolicy().hasHeightForWidth())
        self.punnett_square_view.setSizePolicy(sizePolicy)
        self.punnett_square_view.setMaximumSize(QtCore.QSize(5000, 5000))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.punnett_square_view.setFont(font)
        self.punnett_square_view.setFocusPolicy(QtCore.Qt.NoFocus)
        self.punnett_square_view.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.punnett_square_view.setLineWidth(1)
        self.punnett_square_view.setMidLineWidth(0)
        self.punnett_square_view.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.punnett_square_view.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.punnett_square_view.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.punnett_square_view.setAutoScroll(True)
        self.punnett_square_view.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.punnett_square_view.setTabKeyNavigation(False)
        self.punnett_square_view.setProperty("showDropIndicator", True)
        self.punnett_square_view.setDragEnabled(True)
        self.punnett_square_view.setAlternatingRowColors(False)
        self.punnett_square_view.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.punnett_square_view.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.punnett_square_view.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.punnett_square_view.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.punnett_square_view.setGridStyle(QtCore.Qt.SolidLine)
        self.punnett_square_view.setCornerButtonEnabled(False)
        self.punnett_square_view.setObjectName("punnett_square_view")
        self.punnett_square_view.setColumnCount(0)
        self.punnett_square_view.setRowCount(0)
        self.punnett_square_view.horizontalHeader().setVisible(True)
        self.punnett_square_view.horizontalHeader().setCascadingSectionResizes(False)
        self.punnett_square_view.horizontalHeader().setDefaultSectionSize(150)
        self.punnett_square_view.horizontalHeader().setHighlightSections(False)
        self.punnett_square_view.horizontalHeader().setMinimumSectionSize(150)
        self.punnett_square_view.horizontalHeader().setSortIndicatorShown(False)
        self.punnett_square_view.horizontalHeader().setStretchLastSection(True)
        self.punnett_square_view.verticalHeader().setVisible(True)
        self.punnett_square_view.verticalHeader().setCascadingSectionResizes(False)
        self.punnett_square_view.verticalHeader().setDefaultSectionSize(150)
        self.punnett_square_view.verticalHeader().setHighlightSections(False)
        self.punnett_square_view.verticalHeader().setMinimumSectionSize(150)
        self.punnett_square_view.verticalHeader().setSortIndicatorShown(False)
        self.punnett_square_view.verticalHeader().setStretchLastSection(True)
        self.verticalLayout_2.addWidget(self.punnett_square_view)
        self.gridLayout_2.addWidget(self.groupBox_2, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.f1_input, self.f2_input)
        MainWindow.setTabOrder(self.f2_input, self.solve_punnett_square_button)
        MainWindow.setTabOrder(self.solve_punnett_square_button, self.punnett_square_view)
        MainWindow.setTabOrder(self.punnett_square_view, self.data_view)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Punnytt"))
        self.groupBox.setTitle(_translate("MainWindow", "Outcome Data"))
        self.data_view.setSortingEnabled(True)
        self.data_view.headerItem().setText(0, _translate("MainWindow", "Genotype Outcome"))
        self.data_view.headerItem().setText(1, _translate("MainWindow", "Probability of Outcome Occurance (%)"))
        self.f1_input_label.setText(_translate("MainWindow", "P1 (Parent 1) Alleles:"))
        self.f2_input_label.setText(_translate("MainWindow", "P2 (Parent 2) Alleles:"))
        self.solve_punnett_square_button.setText(_translate("MainWindow", "Solve!"))
        self.f2_input.setPlaceholderText(_translate("MainWindow", "e.g. ttRr"))
        self.f1_input.setPlaceholderText(_translate("MainWindow", "e.g. TtRr"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Solved Punnett Square"))
        self.punnett_square_view.setSortingEnabled(False)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
